name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    if: contains(github.event.head_commit.message, 'build_it')
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
        ls dist
    - name: Create file in dist
      run: echo "This is a sample file in dist" > dist/sample.txt
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'dist'
        author_name: abhijitvtor10
        author_email: abhijit.vtor@gmail.com
        message: 'Build Webpack Now'
