name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    if: contains(github.event.head_commit.message, 'build_it')
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: remove dist
      run:  rm -rf dist
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'dist'
        author_name: abhijitvtor10
        author_email: abhijit.vtor@gmail.com
        message: 'Build Webpack Now'

    - name: build webpack dist
      run: npx webpack --config webpack.config.js

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'dist'
        author_name: abhijitvtor10
        author_email: abhijit.vtor@gmail.com
        message: 'Build Webpack Now'
